server:
  port: 8081

spring:
  application:
    name: web-client
  datasource:
    url: jdbc:h2:file:~/spring-h2-database/users-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

api:
  storage:
    basicUri: ${API_PRODUCT_INVENTORY_URI:http://localhost:8082/}
