server:
  port: 8765

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: web-client
          uri: http://localhost:8081/
          predicates:
            - Path=/**
